POST http://127.0.0.1:3000/api/register/professor HTTP/1.1
Content-Type: application/json

{
    "email": "ha.enrqz@gmail.com",
    "password": "123",
    "first_name": "Hector",
    "middle_name": "Alejandro",
    "last_name": "Enriquez",
    "age": 22,
    "gender": "male",
    "department": "Engineering"
}